// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, ResultState) {
  ResultStateSuccess = 0,
  ResultStateError = 1,
};

@class TimeLimitResult;
@class UsedApp;

@interface TimeLimitResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithState:(ResultState)state
    message:(NSString *)message;
@property(nonatomic, assign) ResultState state;
@property(nonatomic, copy) NSString * message;
@end

@interface UsedApp : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    name:(NSString *)name
    minutesUsed:(NSNumber *)minutesUsed;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, strong) NSNumber * minutesUsed;
@end

/// The codec used by FlutterJitsiMeetApi.
NSObject<FlutterMessageCodec> *FlutterJitsiMeetApiGetCodec(void);

@protocol FlutterJitsiMeetApi
- (void)getPlatformVersionWithCompletion:(void(^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)getAppsWithCompletion:(void(^)(NSArray<UsedApp *> *_Nullable, FlutterError *_Nullable))completion;
- (void)setAppTimeLimitAppId:(NSString *)appId durationInMinutes:(NSNumber *)durationInMinutes completion:(void(^)(TimeLimitResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FlutterJitsiMeetApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FlutterJitsiMeetApi> *_Nullable api);

NS_ASSUME_NONNULL_END
