// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum ResultState {
  success,
  error,
}

class TimeLimitResult {
  TimeLimitResult({
    required this.state,
    required this.message,
  });

  ResultState state;

  String message;

  Object encode() {
    return <Object?>[
      state.index,
      message,
    ];
  }

  static TimeLimitResult decode(Object result) {
    result as List<Object?>;
    return TimeLimitResult(
      state: ResultState.values[result[0]! as int]
,
      message: result[1]! as String,
    );
  }
}

class UsedApp {
  UsedApp({
    required this.id,
    required this.name,
    required this.minutesUsed,
  });

  String id;

  String name;

  int minutesUsed;

  Object encode() {
    return <Object?>[
      id,
      name,
      minutesUsed,
    ];
  }

  static UsedApp decode(Object result) {
    result as List<Object?>;
    return UsedApp(
      id: result[0]! as String,
      name: result[1]! as String,
      minutesUsed: result[2]! as int,
    );
  }
}

class _FlutterJitsiMeetApiCodec extends StandardMessageCodec {
  const _FlutterJitsiMeetApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is TimeLimitResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is UsedApp) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return TimeLimitResult.decode(readValue(buffer)!);
      
      case 129:       
        return UsedApp.decode(readValue(buffer)!);
      
      default:

        return super.readValueOfType(type, buffer);
      
    }
  }
}

class FlutterJitsiMeetApi {
  /// Constructor for [FlutterJitsiMeetApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterJitsiMeetApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _FlutterJitsiMeetApiCodec();

  Future<String?> getPlatformVersion() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FlutterJitsiMeetApi.getPlatformVersion', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return (replyList[0] as String?);
    }
  }

  Future<List<UsedApp?>> getApps() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FlutterJitsiMeetApi.getApps', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<UsedApp?>();
    }
  }

  Future<TimeLimitResult> setAppTimeLimit(String arg_appId, int arg_durationInMinutes) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FlutterJitsiMeetApi.setAppTimeLimit', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_appId, arg_durationInMinutes]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TimeLimitResult?)!;
    }
  }
}
